// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';

// Widgets
export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS';
export const DELETE_WIDGET_SUCCESS = 'DELETE_WIDGET_SUCCESS';

// Portfolio Posts
export const GET_PORTFOLIO_ITEMS_SUCCESS = 'GET_PORTFOLIO_ITEMS_SUCCESS';
export const DELETE_PORTFOLIO_ITEM_SUCCESS = 'DELETE_PORTFOLIO_ITEM_SUCCESS';


// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';

// Portfolio
export const GET_PORTFOLIO_ITEMS_SUCCESS = 'GET_PORTFOLIO_ITEMS_SUCCESS';
export const DELETE_PORTFOLIO_ITEM_SUCCESS = 'DELETE_PORTFOLIO_ITEM_SUCCESS';
export const ADD_PORTFOLIO_ITEM_SUCCESS = 'ADD_PORTFOLIO_ITEM_SUCCESS';
export const REORDER_PORTFOLIO_ITEM_SUCCESS = 'REORDER_PORTFOLIO_ITEM_SUCCESS';
export const PORTFOLIO_ITEM_SUCCESS = 'PORTFOLIO_ITEM_SUCCESS';